-- Recusa qualquer remoção após uso. Sem CASCADE e sem tocar 012/013.
BEGIN;
SET LOCAL lock_timeout='5s';
LOCK TABLE fechamento_revisoes,fechamento_revisao_adicionais,aprovacoes_negociacao IN ACCESS EXCLUSIVE MODE;
DO $$ BEGIN IF EXISTS(SELECT 1 FROM fechamento_revisoes) OR EXISTS(SELECT 1 FROM fechamento_revisao_adicionais) OR EXISTS(SELECT 1 FROM aprovacoes_negociacao WHERE fechamento_revisao_id IS NOT NULL) OR EXISTS(SELECT 1 FROM auditoria WHERE entidade_tipo='FECHAMENTO_REVISAO') OR EXISTS(SELECT 1 FROM contrato_versoes WHERE snapshot ? 'revisaoOperacional') THEN RAISE EXCEPTION 'Migration 014 já utilizada; rollback destrutivo recusado' USING ERRCODE='23514'; END IF; END $$;
DROP TRIGGER fr_preservar_trg ON fechamento_revisoes;
DROP TRIGGER fr_atualizado_trg ON fechamento_revisoes;
DROP TRIGGER fra_preservar_trg ON fechamento_revisao_adicionais;
DROP TRIGGER fra_atualizado_trg ON fechamento_revisao_adicionais;
DROP TRIGGER fr_validar_trg ON fechamento_revisoes;
DROP TRIGGER fra_validar_trg ON fechamento_revisao_adicionais;
DROP TRIGGER fr_edicao_validar_trg ON contrato_edicoes;
DROP TRIGGER fr_fluxo_validar_trg ON contrato_fluxos;
DROP TRIGGER fr_versao_validar_trg ON contrato_versoes;
DROP TRIGGER fr_assinatura_validar_trg ON contrato_assinaturas;
DROP TRIGGER fr_aprovacao_validar_trg ON aprovacoes_negociacao;
DROP TRIGGER fr_fechamento_proteger_trg ON fechamentos;
DROP TRIGGER fr_adicionais_proteger_trg ON fechamento_adicionais;
DROP TRIGGER fr_base_proteger_trg ON fechamento_revisoes;
DROP TRIGGER fr_agenda_validar_trg ON fechamento_revisoes;
DROP TRIGGER fr_confirmacao_agenda_trg ON fechamentos;
DROP TRIGGER fr_bloqueio_proteger_trg ON bloqueios_agenda;
DROP TRIGGER fr_aprovacao_preservar_trg ON aprovacoes_negociacao;
ALTER TABLE fechamento_revisoes DROP CONSTRAINT fr_aprovacao_fk;
ALTER TABLE aprovacoes_negociacao DROP CONSTRAINT an_revisao_fk, DROP CONSTRAINT an_revisao_ck, DROP CONSTRAINT an_id_revisao_uk;
DROP INDEX an_chave_decisao_uk; DROP INDEX an_revisao_hist_idx;
ALTER TABLE aprovacoes_negociacao DROP COLUMN fechamento_revisao_id, DROP COLUMN fechamento_revisao_numero, DROP COLUMN fechamento_revisao_hash, DROP COLUMN chave_decisao;
DROP FUNCTION kidmais_proteger_bloqueio_revisao();
DROP FUNCTION kidmais_validar_agenda_revisao();
DROP FUNCTION kidmais_proteger_fechamento_em_revisao();
DROP FUNCTION kidmais_validar_revisao_operacional();
DROP FUNCTION kidmais_preservar_aprovacao_revisao();
DROP FUNCTION kidmais_preservar_adicional_revisao();
DROP FUNCTION kidmais_preservar_revisao_operacional();
DROP FUNCTION kidmais_hash_revisao_operacional(rid uuid);
DROP FUNCTION kidmais_ocupacoes_operacionais(inicio date,fim date);
DROP FUNCTION kidmais_lock_datas_revisao(dias date[]);
DROP TABLE fechamento_revisao_adicionais; DROP TABLE fechamento_revisoes;
ALTER TABLE contratos DROP CONSTRAINT contratos_fechamento_id_id_uk;
COMMIT;
