'use client';
import { useCallback,useEffect,useState,useRef } from 'react';
import { adminFetch } from '@/lib/http/admin-fetch';
import type { PosicaoFinanceira } from '@/lib/pagamentos/repositories/alteracao-financeira.repository';
import type { PedidoResolucao } from '@/lib/pagamentos/services/alteracao-financeira.models';
import styles from './financeiro.module.css';
import { propostaDeParcelas, origemApresentacao, dataApresentacao, textoHistorico } from './financeiro-apresentacao';
import { projetarTratamento, serializarEscolhaCredito, type EscolhaCredito } from '@/lib/pagamentos/services/projecao-tratamento';
type Json<T>=T extends bigint?string:T extends Array<infer U>?Json<U>[]:T extends object?{[K in keyof T]:Json<T[K]>}:T;
type Painel=Omit<Json<PosicaoFinanceira>,'pendencias'>&{pendencias:Array<{id:string;versao_nova_id:string;situacao:string;tentativas:Array<{id:string;tentativa:number;estado:string}>}>;origens:Array<{id:string;recebimento_id:string;parcela_id:string;disponivel_centavos:string;valor_bruto?:string;recebido_em?:string;meio_pagamento?:string}>;provas:Array<{id:string;devolucao_id:string;nome_arquivo:string}>;timeline:Array<{id:string;tipo:string;instante:string|null;fonte:string;responsavel?:string;detalhe?:string}>};
const moeda=(v:string|bigint)=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v)/100);
const reais=(v:string)=>`${BigInt(v)/100n},${(BigInt(v)%100n).toString().padStart(2,'0')}`;
function centavos(v:string){const m=/^(\d+)(?:[,.](\d{1,2}))?$/.exec(v.trim());if(!m)throw Error('Informe reais com até duas casas decimais, sem separador de milhar.');return (BigInt(m[1])*100n+BigInt((m[2]??'').padEnd(2,'0'))).toString();}
const label=(s:string)=>s.replaceAll('_',' ').toLowerCase();
export default function FinanceiroContrato({contratoId,onReady}:{contratoId:string;onReady?:()=>void}){
 const [p,setP]=useState<Painel|null>(null),[papel,setPapel]=useState(''),[erro,setErro]=useState(''),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 const [tratamento,setTratamento]=useState(''),[etapa,setEtapa]=useState(0),[reprogramando,setReprogramando]=useState(false),[pedido,setPedido]=useState<PedidoResolucao|null>(null),[sim,setSim]=useState<{delta:string;depois:Painel['posicao']}|null>(null);
 const [escolhaCredito,setEscolhaCredito]=useState<EscolhaCredito|''>('');
 const [devolver,setDevolver]=useState(false),[valor,setValor]=useState(''),[beneficiario,setBeneficiario]=useState(''),[motivo,setMotivo]=useState('');
 const [motivosCancelamento,setMotivosCancelamento]=useState<Record<string,string>>({});
 const [execucao,setExecucao]=useState(''),[dataReal,setDataReal]=useState(''),[observacao,setObservacao]=useState(''),[semProva,setSemProva]=useState(''),[meio,setMeio]=useState('PIX');
 const [movimento,setMovimento]=useState<'receber'|'estornar'|''>(''),[parcelaMov,setParcelaMov]=useState(''),[valorMov,setValorMov]=useState(''),[motivoMov,setMotivoMov]=useState(''),[dataMov,setDataMov]=useState(''),[reprogramarEstorno,setReprogramarEstorno]=useState(false),[vencimentoEstorno,setVencimentoEstorno]=useState('');
 const base=`/api/admin/contratos/${contratoId}/financeiro`;
 const chaves=useRef(new Map<string,string>());
 const load=useCallback(async()=>{const r=await adminFetch(base),b=await r.json();if(!b.ok)throw Error(b.erro);setP(b.data.painel);setPapel(b.data.papel);return b.data.painel as Painel;},[base]);
 useEffect(()=>{let ativo=true;adminFetch(base).then(r=>r.json()).then(b=>{if(!ativo)return;if(!b.ok)throw Error(b.erro);setP(b.data.painel);setPapel(b.data.papel);}).catch(e=>{if(ativo)setErro(e.message);});return()=>{ativo=false;};},[base]);
 async function post(path:string,body:unknown){const json=JSON.stringify(body),identidade=path+json;let chave=chaves.current.get(identidade);if(!chave){chave=crypto.randomUUID();chaves.current.set(identidade,chave);}const r=await adminFetch(base+path,{method:'POST',headers:{'Content-Type':'application/json','Idempotency-Key':chave},body:json}),b=await r.json();if(!b.ok)throw Error(b.erro);return b.data;}
 async function run(work:()=>Promise<void>){setBusy(true);setErro('');setMsg('');try{await work();}catch(e){setErro(e instanceof Error?e.message:'Operação não concluída.');}finally{setBusy(false);}}
 async function registrarMovimento(body:Record<string,unknown>){if(!p)return;const tipo=movimento==='receber'?'recebimentos':'estornos',identidade=tipo+JSON.stringify(body);let chave=chaves.current.get(identidade);if(!chave){chave=crypto.randomUUID();chaves.current.set(identidade,chave);}const r=await adminFetch(`/api/admin/pagamentos/${p.pagamento.id}/${tipo}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,chaveIdempotencia:chave})}),b=await r.json();if(!b.ok)throw Error(b.erro);setMovimento('');await load();setMsg(movimento==='receber'?'Recebimento confirmado.':'Estorno confirmado.');}
 function configurar(atual:Painel,reprogramar=false){
  const alvo=BigInt(reprogramar?atual.posicao.obrigacao:atual.valorVigente),futuro=atual.futuro.filter(i=>BigInt(i.valorCentavos)>0n).map(({parcelaId,valorCentavos,vencimento})=>({parcelaId,valorCentavos,vencimento}));
  const projecao=projetarTratamento(atual.posicao.obrigacao,atual.posicao.liquido,alvo.toString(),atual.posicao.reservado);
  setEscolhaCredito(projecao.opcoes[0]==='NAO_SE_APLICA'?'NAO_SE_APLICA':'');setDevolver(false);
  const versao=reprogramar?atual.reconhecida:atual.vigente;
  const pix=(versao.snapshot.comercial.condicaoPagamento?.forma??versao.snapshot.comercial.formaPagamentoPretendida)==='PIX_AVISTA';
  const proposta=propostaDeParcelas(projecao.saldo,futuro,versao.snapshot.evento.data,pix);
  setPedido({posicaoHash:atual.posicaoHash,...proposta,credito:'NAO_SE_APLICA',decisaoContratante:'NAO_SE_APLICA',justificativa:''});setSim(null);setEtapa(1);setReprogramando(reprogramar);
 }
 useEffect(()=>{if(p||erro)onReady?.();},[p,erro,onReady]);
 if(!p)return <section className={styles.panel}><h2>Financeiro</h2><p role={erro?'alert':undefined}>{erro||'Carregando posição financeira…'}</p></section>;
 const projecao=projetarTratamento(p.posicao.obrigacao,p.posicao.liquido,reprogramando?p.posicao.obrigacao:p.valorVigente,p.posicao.reservado);
 const descricaoCredito=escolhaCredito==='SOLICITAR_DEVOLUCAO'?'Solicitar devolução após regularização':label(escolhaCredito);
 const pend=!p.cobranca.encerrada&&p.pendencias.find(x=>x.versao_nova_id===p.vigente.id&&['PENDENTE','EM_TRATAMENTO'].includes(x.situacao));
 const pendenteProjetado=projetarTratamento(p.posicao.obrigacao,p.posicao.liquido,p.valorVigente,p.posicao.reservado);
 const versaoDoPlano=reprogramando?p.reconhecida:p.vigente;
 const pixAvista=(versaoDoPlano.snapshot.comercial.condicaoPagamento?.forma??versaoDoPlano.snapshot.comercial.formaPagamentoPretendida)==='PIX_AVISTA';
 const temSaldo=BigInt(projecao.saldo)>0n;
 const resumo=(valores:Array<[string,string]>)=><dl className={styles.metrics}>{valores.map(([nome,value])=><div key={nome}><dt>{nome}</dt><dd>{moeda(value)}</dd></div>)}</dl>;
 const camposProjecao=(projetado:typeof projecao):Array<[string,string]>=>[['Valor da versão vigente',p.valorVigente],['Obrigação reconhecida',p.posicao.obrigacao],['Delta projetado',projetado.delta],['Recebido líquido',p.posicao.liquido],['Saldo projetado',projetado.saldo],['Crédito projetado',projetado.credito]];
 return <section className={styles.panel} aria-label="Financeiro da contratação">
 <h2>Financeiro da contratação</h2><p>Versão vigente: <strong>V{p.vigente.numero_versao}</strong> · Versão reconhecida financeiramente: <strong>V{p.reconhecida.numero_versao}</strong></p>
 <p>Obrigação original V{p.original.numero_versao}: {moeda(BigInt(Math.round(Number(p.pagamento.valor_total_contratado)*100)))} · estado original: {label(p.pagamento.status)}.</p>
 {p.cobranca.encerrada&&<p role="status">Cobranças encerradas pelo cancelamento. Valores e movimentos anteriores permanecem no histórico.{p.cobranca.acertoAdministrativoPendente?' Acerto financeiro administrativo pendente: confira os recebimentos e defina retenção, devolução ou outro acerto. Nenhuma devolução ou baixa de recebimento foi efetuada automaticamente.':''}</p>}
 <dl className={styles.metrics}>{[[p.cobranca.encerrada?'Obrigação histórica':'Obrigação consolidada',p.posicao.obrigacao],['Recebido líquido',p.posicao.liquido],['Saldo a receber',p.cobranca.saldoACobrar],['Crédito total',p.posicao.credito],['Reservado para devolução',p.posicao.reservado],['Crédito disponível',p.posicao.disponivel],['Devolvido',p.posicao.devolvido]].map(([nome,value])=><div key={nome}><dt>{nome}</dt><dd>{moeda(value)}</dd></div>)}</dl>
 {pend&&<section aria-label="Resumo da alteração pendente"><h3>Alteração financeira pendente — projeção</h3>{resumo(camposProjecao(pendenteProjetado))}</section>}
 {erro&&<p role="alert" className={styles.error}>{erro}</p>}{msg&&<p role="status">{msg}</p>}
 <div className={styles.actions}><button disabled={busy} onClick={()=>run(async()=>{await load();setMsg('Posição atualizada.');})}>Atualizar posição</button>
 {pend&&<button disabled={busy||etapa>0} onClick={()=>run(async()=>{let atual=p;const aberta=pend.tentativas.find(t=>t.estado==='EM_TRATAMENTO');if(aberta)setTratamento(aberta.id);else{const r=await post(`/pendencias/${pend.id}/tratamentos`,{posicaoHash:p.posicaoHash});setTratamento(r.resultado.tratamentoId);atual=await load();}configurar(atual);})}>{pend.situacao==='EM_TRATAMENTO'?'Retomar tratamento':'Abrir tratamento da alteração'}</button>}
 {!p.cobranca.encerrada&&p.cronograma&&BigInt(pend?pendenteProjetado.saldo:p.posicao.saldo)>0n&&<button disabled={busy||etapa>0} onClick={()=>{setTratamento('');configurar(p,true);}}>Reprogramar cronograma</button>}
 {BigInt(p.posicao.disponivel)>0n&&<button disabled={busy} onClick={()=>setDevolver(!devolver)}>Solicitar devolução de crédito</button>}</div>
 <h3>Alterações financeiras</h3>{p.pendencias.length?p.pendencias.map(x=><div key={x.id}><p>{x.versao_nova_id===p.vigente.id?`V${p.vigente.numero_versao}`:'Versão anterior'}: <strong>{label(x.situacao)}</strong></p>{x.tentativas.map(t=><p key={t.id}>Tentativa #{t.tentativa}: {label(t.estado)}</p>)}</div>):<p>{p.cobranca.acertoAdministrativoPendente?'Acerto administrativo do cancelamento pendente.':'Sem pendência financeira registrada.'}</p>}
 {etapa>0&&pedido&&<fieldset disabled={busy} className={styles.wizard}><legend>{reprogramando?'Reprogramação':'Resolver alteração financeira'} · Etapa {etapa} de 4</legend>
 {etapa===1&&<><h3>1. Conferir a alteração</h3>{resumo(camposProjecao(projecao))}<p>Impactos: {p.motivos.map(label).join(', ')||'Programação das parcelas'}. Nenhum recebimento é criado pela resolução.</p></>}
 {etapa===2&&<><h3>2. Definir o tratamento</h3><p>Composição do saldo: obrigação reconhecida {moeda(p.posicao.obrigacao)} + delta {moeda(projecao.delta)} = obrigação projetada {moeda(reprogramando?p.posicao.obrigacao:p.valorVigente)}. Recebido líquido: {moeda(p.posicao.liquido)}.</p><p><strong>Saldo a regularizar: {moeda(projecao.saldo)}</strong> · crédito antes da alteração: {moeda(p.posicao.credito)}.</p>{pixAvista&&temSaldo&&<p>PIX à vista: uma única cobrança pelo saldo total ainda devido. Confira o vencimento antes de confirmar.</p>}<label>Saldo futuro<select aria-label="Saldo futuro" value={pedido.modo} onChange={e=>{const modo=e.target.value as PedidoResolucao['modo'];setPedido({...pedido,modo,parcelas:modo==='SEM_SALDO'?[]:pedido.parcelas});}}>{temSaldo?<>{!pixAvista&&<option value="MANTER_E_COMPLEMENTAR">Preservar parcelas e complementar</option>}<option value="REPROGRAMAR">{pixAvista?'Cobrança única do saldo (PIX à vista)':'Reprogramar saldo'}</option>{!pixAvista&&<option value="PERSONALIZADO">Compor cronograma personalizado</option>}</>:<option value="SEM_SALDO">Sem saldo a receber</option>}</select></label>
 <p>Crédito projetado: <strong>{moeda(projecao.credito)}</strong></p><p>Esta projeção não altera o crédito disponível. O reconhecimento ocorre somente ao confirmar a regularização.</p>
 <label>Crédito<select aria-label="Crédito" value={escolhaCredito} onChange={e=>{const escolha=e.target.value as EscolhaCredito;setEscolhaCredito(escolha);setPedido({...pedido,credito:serializarEscolhaCredito(escolha,projecao)});setSim(null);}}>{projecao.opcoes[0]!=='NAO_SE_APLICA'&&<option value="" disabled>Selecione o tratamento do crédito</option>}{projecao.opcoes.map(opcao=><option key={opcao} value={opcao}>{{NAO_SE_APLICA:'Não se aplica',MANTER:'Manter crédito na contratação',SOLICITAR_DEVOLUCAO:'Solicitar devolução',APROVEITAR:'Autorizar aproveitamento nesta contratação'}[opcao]}</option>)}</select></label>
 {escolhaCredito==='SOLICITAR_DEVOLUCAO'&&<p>Após confirmar a regularização, preencha e confirme a solicitação de devolução. Esta escolha ainda não reserva crédito nem registra saída financeira.</p>}
 {p.motivos.includes('CONTRATANTE')&&<label>Troca de contratante<select value={pedido.decisaoContratante} onChange={e=>setPedido({...pedido,decisaoContratante:e.target.value as PedidoResolucao['decisaoContratante']})}><option value="NAO_SE_APLICA">Selecione uma decisão</option><option value="MANTER_APROVEITAMENTO">Manter valores aplicados à contratação</option><option value="APROVEITAMENTO_AUTORIZADO">Aproveitamento autorizado pelo pagador anterior</option><option value="DEVOLUCAO_AO_PAGADOR_ANTERIOR" disabled={BigInt(p.posicao.liquido)<=BigInt(p.valorVigente)+BigInt(p.posicao.reservado)}>Devolver apenas crédito disponível ao pagador anterior, após esta resolução</option></select></label>}
 <label>Justificativa e autorização<textarea value={pedido.justificativa} onChange={e=>setPedido({...pedido,justificativa:e.target.value})}/></label></>}
 {etapa===3&&<><h3>3. Conferir parcelas futuras</h3><p>{!temSaldo?'Não há saldo a programar.':pixAvista?'PIX à vista: confira o vencimento da única cobrança pelo saldo total.':'Parcelas preservadas mantêm seus valores e vencimentos. Para reprogramar uma parcela, remova-a desta proposta e inclua uma nova.'}</p>{pedido.parcelas.map((item,i)=><div className={styles.item} key={`${item.parcelaId??'nova'}-${i}`}><span>{item.parcelaId?'Preservada':'Nova'}</span><label>Valor em reais<input aria-label={`Valor da parcela ${i+1}`} defaultValue={reais(item.valorCentavos)} readOnly={!!item.parcelaId||pixAvista} onBlur={e=>{try{const valorCentavos=centavos(e.target.value);setPedido({...pedido,parcelas:pedido.parcelas.map((it,n)=>n===i?{...it,valorCentavos}:it)});setErro('');}catch(err){e.currentTarget.value=reais(item.valorCentavos);setErro(`Valor não aplicado; o valor anterior foi restaurado. ${(err as Error).message}`);}}}/></label><label>Vencimento<input type="date" value={item.vencimento} readOnly={!!item.parcelaId} onChange={e=>setPedido({...pedido,parcelas:pedido.parcelas.map((it,n)=>n===i?{...it,vencimento:e.target.value}:it)})}/></label>{!pixAvista&&<button onClick={()=>setPedido({...pedido,parcelas:pedido.parcelas.filter((_,n)=>n!==i)})}>Remover da proposta</button>}</div>)}{temSaldo&&!pixAvista&&<button onClick={()=>setPedido({...pedido,parcelas:[...pedido.parcelas,{valorCentavos:'100',vencimento:versaoDoPlano.snapshot.evento.data}]})}>Adicionar parcela</button>}<p>Total proposto: {moeda(pedido.parcelas.reduce((a,i)=>a+BigInt(i.valorCentavos),0n))}</p></>}
 {etapa===4&&<><h3>4. Simular e confirmar</h3><p>Justificativa: {pedido.justificativa}</p>{resumo([['Obrigação antes',p.posicao.obrigacao],['Delta',sim?.delta??projecao.delta],['Obrigação depois',sim?.depois.obrigacao??(reprogramando?p.posicao.obrigacao:p.valorVigente)],['Recebido líquido',p.posicao.liquido],['Saldo',sim?.depois.saldo??projecao.saldo],['Crédito',sim?.depois.credito??projecao.credito]])}<h4>Composição do cronograma</h4>{pedido.parcelas.length?<ul>{pedido.parcelas.map((i,n)=><li key={n}>Cobrança {n+1}: {moeda(i.valorCentavos)} — vencimento {dataApresentacao(i.vencimento)} — {i.parcelaId?'parcela preservada':'nova cobrança'}</li>)}</ul>:<p>Sem cobranças futuras: saldo projetado zero.</p>}<p>Total do cronograma: {moeda(pedido.parcelas.reduce((a,i)=>a+BigInt(i.valorCentavos),0n))}</p><p>Decisão sobre crédito: {descricaoCredito}.</p><button onClick={()=>run(async()=>setSim(await post(reprogramando?'/cronograma/simulacao':`/tratamentos/${tratamento}/simulacao`,pedido)))}>Validar simulação</button>{sim&&<><p>Nova obrigação: {moeda(sim.depois.obrigacao)} · saldo: {moeda(sim.depois.saldo)} · crédito: {moeda(sim.depois.credito)}.</p><button onClick={()=>run(async()=>{await post(reprogramando?'/cronograma/reprogramar':`/tratamentos/${tratamento}/resolver`,pedido);setEtapa(0);await load();if(escolhaCredito==='SOLICITAR_DEVOLUCAO'){setValor('');setBeneficiario('');setMotivo('');setDevolver(true);}setMsg('Tratamento confirmado. Nenhum recebimento foi criado.');})}>{reprogramando?'Confirmar reprogramação':'Confirmar tratamento financeiro'}</button></>}</>}
 <div className={styles.actions}>{etapa>1&&<button onClick={()=>{setEtapa(etapa-1);setSim(null);}}>Voltar</button>}{etapa<4&&<button disabled={etapa===2&&(!escolhaCredito||!projecao.opcoes.includes(escolhaCredito))} onClick={()=>setEtapa(etapa+1)}>Continuar</button>}<button onClick={()=>setEtapa(0)}>Fechar sem confirmar</button>{tratamento&&<button onClick={()=>run(async()=>{if(!pedido.justificativa.trim())throw Error('Preencha a justificativa na etapa 2 para cancelar esta tentativa.');await post(`/tratamentos/${tratamento}/cancelar`,{motivo:pedido.justificativa});setEtapa(0);await load();setMsg('Tentativa cancelada. A necessidade financeira continua pendente.');})}>Cancelar tentativa</button>}</div></fieldset>}
 <h3>{p.cobranca.encerrada?'Cobranças encerradas':p.cronograma?'Cronograma consolidado vigente':'Programação do plano original'}</h3><table><thead><tr><th>Parcela</th><th>Vencimento</th><th>Saldo</th></tr></thead><tbody>{p.futuro.map((i,n)=><tr key={i.parcelaId}><td>{n+1}</td><td>{i.vencimento.split('-').reverse().join('/')}</td><td>{moeda(i.valorCentavos)}</td></tr>)}</tbody></table>
 {devolver&&<fieldset disabled={busy}><legend>Solicitar devolução — reserva de crédito</legend><p>A solicitação reserva crédito. A saída financeira só é reconhecida na conclusão por representante autorizado.</p><label>Valor em reais<input value={valor} onChange={e=>setValor(e.target.value)}/></label><label>Beneficiário<input value={beneficiario} onChange={e=>setBeneficiario(e.target.value)}/></label><label>Motivo da solicitação<textarea aria-label="Motivo da solicitação" value={motivo} onChange={e=>setMotivo(e.target.value)}/></label><p>Origens disponíveis (recebimentos originais):</p><ul>{p.origens.filter(o=>BigInt(o.disponivel_centavos)>0n).map(o=><li key={o.id}>{origemApresentacao(o)} · disponível nesta origem: {moeda(o.disponivel_centavos)}<details><summary>Referência técnica</summary>{o.recebimento_id}</details></li>)}</ul><button onClick={()=>run(async()=>{const valorCentavos=centavos(valor);let restante=BigInt(valorCentavos);const origens=[];for(const o of p.origens){const usar=restante<BigInt(o.disponivel_centavos)?restante:BigInt(o.disponivel_centavos);if(usar>0n){origens.push({alocacaoId:o.id,valorCentavos:usar.toString()});restante-=usar;}}if(restante>0n)throw Error('Origens insuficientes.');await post('/devolucoes',{posicaoHash:p.posicaoHash,valorCentavos,beneficiario:{nome:beneficiario},motivo,origens});setDevolver(false);await load();setMsg('Devolução solicitada; crédito reservado.');})}>Confirmar solicitação usando as origens acima, em ordem</button></fieldset>}
 <h3>Devoluções</h3>{p.devolucoes.length===0&&<p>Nenhuma devolução registrada.</p>}{p.devolucoes.map(d=><div className={styles.refund} key={d.id} role="group" aria-label={`Devolução para ${String(d.beneficiario_snapshot.nome??'Beneficiário')}`}><p>{moeda(d.valor_centavos)} · {String(d.beneficiario_snapshot.nome??'Beneficiário')} · <strong>{label(d.estado)}</strong></p>{p.provas.filter(x=>x.devolucao_id===d.id).map(x=><a key={x.id} href={`${base}/devolucoes/${d.id}/comprovantes/${x.id}`}>{x.nome_arquivo}</a>)}{d.estado==='PENDENTE'&&<><label>Comprovante (PDF, JPEG ou PNG)<input type="file" accept="application/pdf,image/png,image/jpeg" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void run(async()=>{const form=new FormData();form.append('arquivo',file);const r=await adminFetch(`${base}/devolucoes/${d.id}/comprovantes`,{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:form}),b=await r.json();if(!b.ok)throw Error(b.erro);await load();});}}/></label><label>Motivo do cancelamento<input aria-label="Motivo do cancelamento" value={motivosCancelamento[d.id]??''} onChange={e=>setMotivosCancelamento({...motivosCancelamento,[d.id]:e.target.value})}/></label><button disabled={busy} onClick={()=>run(async()=>{await post(`/devolucoes/${d.id}/cancelar`,{motivo:motivosCancelamento[d.id]??''});setMotivosCancelamento(atual=>Object.fromEntries(Object.entries(atual).filter(([id])=>id!==d.id)));await load();})}>Cancelar devolução pendente</button>{papel==='REPRESENTANTE_AUTORIZADO'&&<button disabled={busy} onClick={()=>setExecucao(d.id)}>Registrar saída financeira efetivada</button>}</>}
 {execucao===d.id&&d.estado==='PENDENTE'&&<fieldset disabled={busy}><legend>Confirmar devolução realizada</legend><label>Data e hora reais<input type="datetime-local" value={dataReal} onChange={e=>setDataReal(e.target.value)}/></label><label>Meio<select value={meio} onChange={e=>setMeio(e.target.value)}>{['PIX','CARTAO','TRANSFERENCIA','DINHEIRO','OUTRO'].map(m=><option key={m}>{m}</option>)}</select></label><label>Observação da execução<textarea value={observacao} onChange={e=>setObservacao(e.target.value)}/></label><label>Justificativa se não houver comprovante<textarea value={semProva} onChange={e=>setSemProva(e.target.value)}/></label><button onClick={()=>run(async()=>{await post(`/devolucoes/${d.id}/concluir`,{posicaoHash:p.posicaoHash,devolvidoEm:new Date(dataReal).toISOString(),meio,observacao,...(semProva.trim()?{justificativaSemComprovante:semProva}: {})});setExecucao('');await load();setMsg('Devolução concluída e saída financeira registrada.');})}>Confirmo que a saída financeira ocorreu</button></fieldset>}</div>)}
 <h3>Ações financeiras</h3><div className={styles.actions}><button disabled={busy||p.cobranca.encerrada} onClick={()=>{setMovimento('receber');setParcelaMov('');setValorMov('');}}>Registrar recebimento</button><button disabled={busy} onClick={()=>{setMovimento('estornar');setParcelaMov('');setValorMov('');setReprogramarEstorno(false);setVencimentoEstorno(p.reconhecida.snapshot.evento.data);}}>Estornar recebimento</button></div>
 {movimento&&<fieldset disabled={busy}><legend>{movimento==='receber'?'Confirmar recebimento efetivo':'Estorno de lançamento existente'}</legend><label>{movimento==='receber'?'Parcela a receber':'Origem do estorno'}<select aria-label={movimento==='receber'?'Parcela a receber':'Origem do estorno'} value={parcelaMov} onChange={e=>setParcelaMov(e.target.value)}><option value="">Selecione</option>{movimento==='receber'?p.futuro.filter(i=>BigInt(i.valorCentavos)>0n).map((i,n)=><option key={i.parcelaId} value={i.parcelaId}>Parcela {n+1} · {i.vencimento} · {moeda(i.valorCentavos)}</option>):p.origens.filter(o=>BigInt(o.disponivel_centavos)>0n).map(o=><option key={o.id} value={o.id}>{origemApresentacao(o)} · disponível {moeda(o.disponivel_centavos)}</option>)}</select></label><label>Valor do movimento em reais<input value={valorMov} onChange={e=>setValorMov(e.target.value)}/></label><label>Descrição do movimento<textarea value={motivoMov} onChange={e=>setMotivoMov(e.target.value)}/></label>
 {movimento==='receber'?<><label>Meio do recebimento<select value={meio} onChange={e=>setMeio(e.target.value)}>{['PIX','CARTAO','TRANSFERENCIA','DINHEIRO','OUTRO'].map(m=><option key={m}>{m}</option>)}</select></label><label>Data e hora do recebimento<input type="datetime-local" value={dataMov} onChange={e=>setDataMov(e.target.value)}/></label><p>Use a data em que o dinheiro foi recebido. Um adicional ainda não regularizado precisa ser reconhecido antes.</p></>:p.cronograma&&<><label><input type="checkbox" checked={reprogramarEstorno} onChange={e=>setReprogramarEstorno(e.target.checked)}/>Reprogramar explicitamente todo o saldo após este estorno em uma parcela</label>{reprogramarEstorno&&<label>Vencimento da parcela após estorno<input type="date" value={vencimentoEstorno} onChange={e=>setVencimentoEstorno(e.target.value)}/></label>}<p>Quando o estorno reabrir saldo fora do cronograma, a reprogramação é obrigatória e ocorre na mesma confirmação.</p></>}
 <button onClick={()=>run(async()=>{const value=centavos(valorMov);if(!parcelaMov||!motivoMov.trim())throw Error('Selecione a origem/parcela e descreva o movimento.');if(movimento==='receber'){if(!dataMov)throw Error('Informe a data real do recebimento.');await registrarMovimento({valorBruto:Number(value)/100,meioPagamento:meio,recebidoEm:new Date(dataMov).toISOString(),observacoes:motivoMov,alocacoes:[{parcelaId:parcelaMov,valor:Number(value)/100}]});}else{const origem=p.origens.find(o=>o.id===parcelaMov)!;const saldo=BigInt(p.posicao.obrigacao)-BigInt(p.posicao.liquido)+BigInt(value);const reprogramacao=reprogramarEstorno?{posicaoHash:p.posicaoHash,modo:saldo>0n?'REPROGRAMAR':'SEM_SALDO',parcelas:saldo>0n?[{valorCentavos:saldo.toString(),vencimento:vencimentoEstorno}]:[],credito:saldo<0n?'MANTER':'NAO_SE_APLICA',decisaoContratante:'NAO_SE_APLICA',justificativa:motivoMov}:undefined;await registrarMovimento({recebimentoId:origem.recebimento_id,parcelaId:origem.parcela_id,valor:Number(value)/100,motivo:motivoMov,...(reprogramacao?{reprogramacao}:{})});}})}>Confirmar movimento financeiro</button><button onClick={()=>setMovimento('')}>Fechar</button></fieldset>}
 <h3>Linha do tempo financeira</h3><p>O histórico anterior é consultado nos registros existentes. Os novos eventos começam na implantação deste bloco.</p><ol>{p.timeline.map(e=><li key={e.id}><strong>{label(e.tipo)}</strong> · {e.instante?new Date(e.instante).toLocaleString('pt-BR'):'Data no registro de origem'}{e.responsavel&&` · ${e.responsavel}`}<p>{textoHistorico(e.detalhe)}</p></li>)}</ol>
 </section>;
}
