/* eslint-disable @typescript-eslint/no-require-imports */
// Aplicação local autorizada somente com evidência isolada da mesma versão de SQL.
const fs=require('node:fs'),crypto=require('node:crypto'),assert=require('node:assert/strict');const {Client}=require('pg');const {fingerprint,catalog,paths}=require('./migration-014.validation.cjs');
const sha=x=>crypto.createHash('sha256').update(x).digest('hex');
async function main(){const {dest}=JSON.parse(fs.readFileSync('.tmp/checkpoint-014.json'));assert.match(dest,/^\.backups\/pre-014-\d+$/);const evidence=JSON.parse(fs.readFileSync(dest+'/014-teste-isolado.json')),up=fs.readFileSync(paths.up,'utf8');assert(evidence.integrity&&evidence.results.length>=38,'Testes estruturais incompletos');assert.equal(evidence.sha256Migration,sha(up),'SQL difere do testado');
 const manifest=JSON.parse(fs.readFileSync(dest+'/manifesto.json'));for(const f of manifest.filter(x=>/schema_mvp_kidmais\.sql$|database\/migrations\/|^\.env.local$/.test(x.path)))assert.equal(sha(fs.readFileSync(f.path)),f.sha256,'Arquivo anterior alterado: '+f.path);
 const c=new Client({connectionString:process.env.DATABASE_URL});await c.connect();try{assert.equal((await c.query('SELECT current_database() name')).rows[0].name,'kidmais_manager');await c.query('BEGIN');await c.query("SET LOCAL lock_timeout='5s'");await c.query('LOCK TABLE '+Object.keys(evidence.columns).sort().map(x=>'public."'+x+'"').join(',')+' IN ACCESS EXCLUSIVE MODE');const baseline=JSON.parse(fs.readFileSync(dest+'/dados.json'));assert.deepEqual(await fingerprint(c,evidence.columns),baseline,'Dados mudaram desde checkpoint: reinspecionar');
 const before=await catalog(c),expected=JSON.parse(fs.readFileSync(dest+'/catalogo.json'));for(const k of ['columns','constraints','triggers'])assert.deepEqual(before[k],expected[k]);
 await c.query(fs.readFileSync(paths.pre,'utf8'));await c.query(up.replace(/^BEGIN;\n/m,'').replace(/^COMMIT;\s*$/m,''));await c.query(fs.readFileSync(paths.post,'utf8'));assert.deepEqual(await fingerprint(c,evidence.columns),baseline);
 for(const t of ['fechamento_revisoes','fechamento_revisao_adicionais'])assert.equal((await c.query('SELECT count(*)::int n FROM '+t)).rows[0].n,0);
 assert.equal((await c.query('SELECT count(*)::int n FROM aprovacoes_negociacao WHERE num_nonnulls(fechamento_revisao_id,fechamento_revisao_numero,fechamento_revisao_hash,chave_decisao)>0')).rows[0].n,0);
 const after=await catalog(c);await c.query('COMMIT');fs.writeFileSync(dest+'/014-aplicacao-local.json',JSON.stringify({aplicada:true,banco:'kidmais_manager',sha256Migration:sha(up),testes:evidence.results.length,tabelasAntes:38,tabelasDepois:40,projecoesAnterioresPreservadas:baseline,novasTabelasVazias:true,zeroBackfill:true},null,2));fs.writeFileSync(dest+'/014-catalogo-local.json',JSON.stringify(after,null,2));console.log('Migration 014 aplicada: 40 tabelas, duas novas vazias, 38 projeções preservadas integralmente.');
 }catch(e){await c.query('ROLLBACK');throw e;}finally{await c.end();}}
main().catch(e=>{console.error(e.code,e.message);process.exitCode=1;});
