/* eslint-disable @typescript-eslint/no-require-imports -- Teste Node CommonJS. */
const assert = require('node:assert/strict');
const { spawnSync } = require('node:child_process');
const test = require('node:test');
const { PEPPER_OTP_STAGING, construirAmbienteFilho, selecionarSuites, todasSuites, validarConfiguracao } = require('./regressao-v1-staging.cjs');

const urlStaging = 'postgresql://kidmais_staging:senha-sintetica@staging-db.exemplo.invalid:5432/kidmais_staging?sslmode=verify-full';
function ambienteValido() { return { KIDMAIS_REGRESSAO_STAGING: 'SIM', KIDMAIS_STAGING_DATABASE_URL: urlStaging, KIDMAIS_STAGING_DATABASE_NAME: 'kidmais_staging', KIDMAIS_STAGING_DATABASE_HOST: 'staging-db.exemplo.invalid' }; }

test('recusa ausência da flag explícita', () => { const env=ambienteValido();delete env.KIDMAIS_REGRESSAO_STAGING;assert.throws(()=>validarConfiguracao(env),/deve ser SIM/); });
test('recusa ausência da URL mesmo se DATABASE_URL estiver presente', () => { const env={...ambienteValido(),DATABASE_URL:urlStaging};delete env.KIDMAIS_STAGING_DATABASE_URL;assert.throws(()=>validarConfiguracao(env),/KIDMAIS_STAGING_DATABASE_URL é obrigatória/); });
test('recusa kidmais_manager', () => { const env=ambienteValido();env.KIDMAIS_STAGING_DATABASE_URL='postgresql://usuario:senha@staging-db.exemplo.invalid:5432/kidmais_manager?sslmode=require';env.KIDMAIS_STAGING_DATABASE_NAME='kidmais_manager';assert.throws(()=>validarConfiguracao(env),/banco de produção/); });
test('recusa nome de banco de produção', () => { const env=ambienteValido();env.KIDMAIS_STAGING_DATABASE_URL='postgresql://usuario:senha@staging-db.exemplo.invalid:5432/kidmais_producao?sslmode=require';env.KIDMAIS_STAGING_DATABASE_NAME='kidmais_producao';assert.throws(()=>validarConfiguracao(env),/banco de produção/); });
test('recusa destino idêntico à URL de produção', () => { assert.throws(()=>validarConfiguracao({...ambienteValido(),KIDMAIS_PRODUCTION_DATABASE_URL:urlStaging}),/destino de produção/); });
test('recusa localhost em staging cloud', () => { const env=ambienteValido();env.KIDMAIS_STAGING_DATABASE_URL='postgresql://usuario:senha@127.0.0.1:5432/kidmais_staging?sslmode=require';env.KIDMAIS_STAGING_DATABASE_HOST='127.0.0.1';assert.throws(()=>validarConfiguracao(env),/recusa localhost/); });
test('recusa conexão sem TLS explícito', () => { const env=ambienteValido();env.KIDMAIS_STAGING_DATABASE_URL='postgresql://usuario:senha@staging-db.exemplo.invalid:5432/kidmais_staging';assert.throws(()=>validarConfiguracao(env),/TLS é obrigatório/); });
test('aceita banco remoto com nome exato e TLS', () => { const config=validarConfiguracao(ambienteValido());assert.equal(config.databaseName,'kidmais_staging');assert.equal(config.databaseHost,'staging-db.exemplo.invalid'); });
test('sem argumentos seleciona as sete suítes em ordem', () => { assert.deepEqual(selecionarSuites([]),todasSuites); });
test('as sete suítes usam os mesmos arquivos homologados pelo runner local', () => { assert.deepEqual(todasSuites.map(([nome,comando])=>[nome,comando.at(-1)]),[['identidade-repository',"require('./scripts/identidade-repository.integration.ts')"],['identidade-service',"require('./scripts/identidade-service.integration.ts')"],['identidade-fechamento',"require('./scripts/identidade-fechamento.integration.ts')"],['jornada-fechamento-contrato-otp-pagamento','./scripts/condicao-pagamento.integration.cjs'],['pagamentos-engenharia','./scripts/pagamentos-engenharia.integration.cjs'],['pagamentos-http','./scripts/pagamentos-http.integration.cjs'],['festa-vigencia-remarcacao','./scripts/festa-016-vigencia.cjs']]); });
test('com argumento seleciona somente a suíte solicitada', () => { assert.deepEqual(selecionarSuites(['identidade-repository']).map(([nome])=>nome),['identidade-repository']); });
test('recusa suíte inexistente', () => { assert.throws(()=>selecionarSuites(['nao-existe']),/Suíte inexistente/); });
test('ambiente filho recebe somente a URL de staging e segredos sintéticos', () => { const pai={...ambienteValido(),DATABASE_URL:'postgresql://usuario:real@producao.invalid:5432/kidmais_manager',IDENTIDADE_OTP_PEPPER:'nao-deve-ser-herdado'};const filho=construirAmbienteFilho(pai,validarConfiguracao(pai));assert.equal(filho.DATABASE_URL,urlStaging);assert.equal(filho.IDENTIDADE_OTP_PEPPER,PEPPER_OTP_STAGING);assert.equal(filho.FESTA_ENABLED,'true');assert.equal(filho.DATABASE_SSL_REJECT_UNAUTHORIZED,'true'); });
test('harness de Festa aceita o ambiente filho de staging sem artefatos locais', () => { const env=construirAmbienteFilho(ambienteValido(),validarConfiguracao(ambienteValido()));const resultado=spawnSync(process.execPath,['-e',"require('./scripts/festa-016-test-environment.cjs').assertAutomated()"],{cwd:process.cwd(),env,encoding:'utf8'});assert.equal(resultado.status,0,resultado.stderr); });
